### PR TITLE
Task-5 AWS Simple Storage Service - S3

### PR DESCRIPTION
**Pull request by kastrubait**
Task: https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task5-import-to-s3/task.md
Done 22.09.2021 / Deadline 22.09.2021
Score: 8 / 8 (?)

***Evaluation criteria***
- [x] File serverless.yml contains configuration for **importProductsFile** function
- [x] The **importProductsFile** lambda function returns a correct response which can be used to upload a file into the S3 bucket
- [x] Frontend application is integrated with **importProductsFile** lambda
- [x] The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda

***Additional tasks***
 - [x] (for JS only) - async/await is used in lambda functions (+1)
 - [x] (All languages) - **importProductsFile** lambda is covered by unit tests ((for JS only) aws-sdk-mock can be used to mock S3 methods - https://www.npmjs.com/package/aws-sdk-mock)
 // _tests add, but getSignedUrl doesn't mock correctly when called asynchronously_
 - [x] (All languages) - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into **parsed** folder, and then deleted from uploaded folder) (+1)
 
**Frontend**
 -  https://github.com/kastrubait/shop-angular-cloudfront/pull/4
 - https://d1mkje9otd9k5.cloudfront.net/admin/products

### CODE REVIEW

**Comment by Nadya-Ponka** [comment]
Hello Tatsiana. When I try to upload files from front I've got a mistake:
image

You should set appropriate headers. It worked for me
image

**Comment by Nadya-Ponka** [comment]
Let me know if you correct it

**Comment by Nadya-Ponka** [comment]
Hi! Good job! For signedUrl mock worked:
test('Get correct mocked-url if result correct', async () => {
	const MOCKED_URL = 'https://mocked-url.com';
	AWSMock.mock('S3', 'getSignedUrl', MOCKED_URL);

	const response = await importProductsFile(event);
	expect(JSON.parse(response.body)).toEqual(MOCKED_URL);
});

**Comment by kastrubait** [comment]
> Hi! Good job! For signedUrl mock worked:
> test('Get correct mocked-url if result correct', async () => {
> const MOCKED_URL = 'https://mocked-url.com';
> AWSMock.mock('S3', 'getSignedUrl', MOCKED_URL);
> 
> ```
> const response = await importProductsFile(event);
> expect(JSON.parse(response.body)).toEqual(MOCKED_URL);
> ```
> 
> });



> Привет! Молодец! Для signedUrl сработал макет:
> test ('Получить правильный mocked-url, если результат правильный', async () => {
> const MOCKED_URL = ' https://mocked-url.com ';
> AWSMock.mock ('S3', 'getSignedUrl' , MOCKED_URL);
> 
> ```
> const response = await importProductsFile(event);
> expect(JSON.parse(response.body)).toEqual(MOCKED_URL);
> ```
> 
> });

This is the first thing I tried. But for some reason, it doesn't work for me ((

**Pull request merged**
