### PR TITLE
Task-6 AWS SQS / SNS

### PR DESCRIPTION
**Pull request by kastrubait**
Task: https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task6-async-services-integration-sqs-sns/task.md
Done 09.10.2021 / Deadline 04.10.2021
Score: 5 / 6 (?)

**Evaluation criteria**

- [x] File serverless.yml contains configuration for catalogBatchProcess function
- [x] File serverless.yml contains policies to allow lambda catalogBatchProcess function to interact with SNS and SQS
- [x] File serverless.yml contains configuration for SQS catalogItemsQueue
- [x] File serverless.yml contains configuration for SNS Topic createProductTopic and email subscription

**Additional tasks**

( - ) catalogBatchProcess lambda is covered by unit tests
(+1) set a Filter Policy for SNS createProductTopic in serverless.yml (Create an additional email subscription and distribute messages to different emails depending on the filter for any product attribute)
 
**Frontend**

Task6 shop-angular-cloudfront#4
https://d1mkje9otd9k5.cloudfront.net/admin/products

### CODE REVIEW

**Comment by fetchMachine** [comment]
Так дедлайн кроссчека 9 Октября 23.59, позже никак @kastrubait

**Comment by LyssenkoAlex** [comment]
да без проблем.

**Comment by kastrubait** [comment]
> да без проблем.

Привет. Я запушила решение.

**Comment by kastrubait** [comment]
> Так дедлайн кроссчека 9 Октября 23.59, позже никак @kastrubait

Привет, да знаю)) Я запушила решение утром. @fetchMachine

**Pull request merged**
